//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductComing
    {
        public int IDProductComing { get; set; }
        public Nullable<int> IDComing { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Coming Coming { get; set; }
        public virtual Product Product { get; set; }
    }
}
